#!/bin/bash

# Post 19 - 考试周急救
cat > post-19.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 19</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#ff0844,#ffb199);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold;margin-bottom:20px}.urgent{background:rgba(255,255,255,0.95);border-radius:20px;padding:40px;flex:1}.step{background:#fff;border-radius:15px;padding:20px;margin-bottom:15px}.step-num{font-size:32px;color:#ff0844;font-weight:bold;margin-bottom:10px}.step-text{font-size:20px;color:#333}.footer{text-align:center;color:rgba(255,255,255,0.8);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">🆘 考试周急救指南</h1></div><div class="urgent"><div class="step"><div class="step-num">Step 1</div><div class="step-text">深呼吸，别慌！我陪你一起</div></div><div class="step"><div class="step-num">Step 2</div><div class="step-text">列出所有考试范围和重点</div></div><div class="step"><div class="step-num">Step 3</div><div class="step-text">制定复习计划，优先级排序</div></div><div class="step"><div class="step-num">Step 4</div><div class="step-text">番茄钟专注复习，我来提醒</div></div><div class="step"><div class="step-num">Step 5</div><div class="step-text">定时休息，保证睡眠</div></div></div><div class="footer">🐾 MOMO 陪你度过考试周</div></div></body></html>
EOF

# Post 20 - 新学期计划
cat > post-20.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 20</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#11998e,#38ef7d);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.goals{flex:1;display:flex;flex-direction:column;gap:20px}.goal{background:rgba(255,255,255,0.95);border-radius:20px;padding:30px;display:flex;align-items:center;gap:20px}.goal-num{width:60px;height:60px;background:linear-gradient(135deg,#11998e,#38ef7d);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:32px;font-weight:bold;color:#fff}.goal-text{font-size:24px;color:#333;flex:1}.footer{text-align:center;color:rgba(255,255,255,0.8);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">🎯 新学期目标</h1></div><div class="goals"><div class="goal"><div class="goal-num">1</div><div class="goal-text">GPA 提升到 3.8+</div></div><div class="goal"><div class="goal-num">2</div><div class="goal-text">掌握 Python 编程</div></div><div class="goal"><div class="goal-num">3</div><div class="goal-text">通过英语六级</div></div><div class="goal"><div class="goal-num">4</div><div class="goal-text">参加 2 个比赛</div></div><div class="goal"><div class="goal-num">5</div><div class="goal-text">坚持运动每周 3 次</div></div></div><div class="footer">🐾 MOMO 帮你实现每个目标</div></div></body></html>
EOF

# Post 21 - 求职面试
cat > post-21.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 21</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#667eea,#764ba2);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.content{flex:1;background:rgba(255,255,255,0.95);border-radius:25px;padding:40px}.tip{background:#fff;border-radius:15px;padding:25px;margin-bottom:20px}.tip-title{font-size:24px;color:#667eea;font-weight:bold;margin-bottom:10px}.tip-text{font-size:18px;color:#666}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">💼 面试准备清单</h1></div><div class="content"><div class="tip"><div class="tip-title">✅ 简历优化</div><div class="tip-text">我帮你检查简历，突出亮点</div></div><div class="tip"><div class="tip-title">✅ 常见问题</div><div class="tip-text">模拟面试，练习回答</div></div><div class="tip"><div class="tip-title">✅ 公司调研</div><div class="tip-text">了解公司背景和文化</div></div><div class="tip"><div class="tip-title">✅ 技术复习</div><div class="tip-text">复习核心知识点</div></div><div class="tip"><div class="tip-title">✅ 心态调整</div><div class="tip-text">相信自己，你已经准备好了</div></div></div><div class="footer">🐾 MOMO 祝你面试成功</div></div></body></html>
EOF

# Post 22 - 实习日常
cat > post-22.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 22</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#f093fb,#f5576c);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.timeline{flex:1;display:flex;flex-direction:column;gap:15px}.event{background:rgba(255,255,255,0.95);border-radius:15px;padding:20px;display:flex;align-items:center;gap:15px}.time{font-size:24px;color:#f5576c;font-weight:bold;min-width:80px}.desc{font-size:18px;color:#333;flex:1}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">☕ 实习第一天</h1></div><div class="timeline"><div class="event"><div class="time">9:00</div><div class="desc">到达公司，办理入职</div></div><div class="event"><div class="time">10:00</div><div class="desc">认识团队成员</div></div><div class="event"><div class="time">11:00</div><div class="desc">熟悉开发环境</div></div><div class="event"><div class="time">14:00</div><div class="desc">第一个任务：写个小脚本</div></div><div class="event"><div class="time">18:00</div><div class="desc">完成！团队聚餐</div></div></div><div class="footer">🐾 MOMO 陪你开启职业生涯</div></div></body></html>
EOF

# Post 23 - 团队协作
cat > post-23.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 23</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#4facfe,#00f2fe);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.features{flex:1;display:grid;grid-template-columns:repeat(2,1fr);gap:20px}.feature{background:rgba(255,255,255,0.95);border-radius:20px;padding:30px;text-align:center}.icon{font-size:60px;margin-bottom:15px}.name{font-size:22px;color:#333;font-weight:bold}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">👥 团队协作神器</h1></div><div class="features"><div class="feature"><div class="icon">📋</div><div class="name">任务分配</div></div><div class="feature"><div class="icon">💬</div><div class="name">即时沟通</div></div><div class="feature"><div class="icon">📊</div><div class="name">进度追踪</div></div><div class="feature"><div class="icon">📁</div><div class="name">文件共享</div></div></div><div class="footer">🐾 MOMO 让团队协作更高效</div></div></body></html>
EOF

# Post 24 - 远程办公
cat > post-24.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 24</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#fa709a,#fee140);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.tips{flex:1;display:flex;flex-direction:column;gap:20px}.tip{background:rgba(255,255,255,0.95);border-radius:15px;padding:25px;display:flex;align-items:center;gap:20px}.icon{font-size:50px}.text{font-size:22px;color:#333;flex:1}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">🏠 远程办公技巧</h1></div><div class="tips"><div class="tip"><div class="icon">⏰</div><div class="text">固定作息时间</div></div><div class="tip"><div class="icon">👔</div><div class="text">穿得正式点</div></div><div class="tip"><div class="icon">📵</div><div class="text">减少干扰</div></div><div class="tip"><div class="icon">☕</div><div class="text">定时休息</div></div><div class="tip"><div class="icon">💬</div><div class="text">保持沟通</div></div></div><div class="footer">🐾 MOMO 陪你远程办公</div></div></body></html>
EOF

echo "✅ Posts 19-24 created"
