#!/bin/bash

# Post 25 - 会议纪要
cat > post-25.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 25</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#a8edea,#fed6e3);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#333;font-weight:bold}.content{flex:1;background:rgba(255,255,255,0.95);border-radius:25px;padding:40px}.section{margin-bottom:25px}.section-title{font-size:28px;color:#667eea;font-weight:bold;margin-bottom:15px}.item{font-size:20px;color:#666;margin-bottom:10px;padding-left:20px}.item:before{content:"•";color:#667eea;font-weight:bold;margin-right:10px}.footer{text-align:center;color:rgba(0,0,0,0.5);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">📝 会议纪要整理</h1></div><div class="content"><div class="section"><div class="section-title">✅ 讨论内容</div><div class="item">项目进度汇报</div><div class="item">技术方案讨论</div><div class="item">资源分配</div></div><div class="section"><div class="section-title">📋 待办事项</div><div class="item">小王 - 周三前完成原型</div><div class="item">小李 - 周五前提交代码</div></div><div class="section"><div class="section-title">⏰ 下次会议</div><div class="item">下周一上午 10 点</div></div></div><div class="footer">🐾 MOMO 自动整理会议纪要</div></div></body></html>
EOF

# Post 26 - 数据分析
cat > post-26.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 26</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#667eea,#764ba2);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.chart{flex:1;background:rgba(255,255,255,0.95);border-radius:25px;padding:40px;display:flex;align-items:flex-end;justify-content:space-around}.bar{width:80px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:10px 10px 0 0;text-align:center}.bar span{display:block;color:#fff;font-size:24px;font-weight:bold;padding:10px}.label{color:#333;font-size:18px;margin-top:10px}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">📊 数据分析报告</h1></div><div class="chart"><div class="bar"><span>85%</span><div class="label">周一</div></div><div class="bar"><span>92%</span><div class="label">周二</div></div><div class="bar"><span>78%</span><div class="label">周三</div></div><div class="bar"><span>95%</span><div class="label">周四</div></div><div class="bar"><span>88%</span><div class="label">周五</div></div></div><div class="footer">🐾 MOMO 帮你分析数据</div></div></body></html>
EOF

# Post 27 - 自动化脚本
cat > post-27.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 27</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#1a1a2e,#16213e);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.code{flex:1;background:#1e1e1e;border-radius:20px;padding:40px;font-family:monospace;font-size:20px;color:#d4d4d4;line-height:1.8}.kw{color:#569cd6}.str{color:#ce9178}.com{color:#6a9955}.footer{text-align:center;color:rgba(255,255,255,0.5);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">🤖 自动化脚本</h1></div><div class="code"><span class="com"># MOMO 帮你写的自动化脚本</span><br><span class="kw">def</span> daily_report():<br>&nbsp;&nbsp;data = <span class="str">get_data()</span><br>&nbsp;&nbsp;report = <span class="str">analyze(data)</span><br>&nbsp;&nbsp;<span class="str">send_email(report)</span><br>&nbsp;&nbsp;<span class="kw">return</span> <span class="str">"✅ 完成"</span><br><br><span class="com"># 每天自动运行</span></div><div class="footer">🐾 MOMO 帮你自动化重复工作</div></div></body></html>
EOF

# Post 28 - Git 协作
cat > post-28.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 28</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#f093fb,#f5576c);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.workflow{flex:1;display:flex;flex-direction:column;gap:20px}.step{background:rgba(255,255,255,0.95);border-radius:15px;padding:25px;display:flex;align-items:center;gap:20px}.num{width:50px;height:50px;background:#f5576c;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:24px;font-weight:bold;color:#fff}.text{font-size:22px;color:#333;flex:1}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">🔀 Git 工作流</h1></div><div class="workflow"><div class="step"><div class="num">1</div><div class="text">git checkout -b feature</div></div><div class="step"><div class="num">2</div><div class="text">开发新功能</div></div><div class="step"><div class="num">3</div><div class="text">git commit -m "feat: xxx"</div></div><div class="step"><div class="num">4</div><div class="text">git push origin feature</div></div><div class="step"><div class="num">5</div><div class="text">创建 Pull Request</div></div></div><div class="footer">🐾 MOMO 帮你管理 Git</div></div></body></html>
EOF

# Post 29 - 部署上线
cat > post-29.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 29</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#11998e,#38ef7d);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.checklist{flex:1;background:rgba(255,255,255,0.95);border-radius:25px;padding:40px}.item{font-size:24px;color:#333;margin-bottom:20px;display:flex;align-items:center;gap:15px}.check{color:#11998e;font-size:32px}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">🚀 部署上线清单</h1></div><div class="checklist"><div class="item"><span class="check">✅</span>代码审查通过</div><div class="item"><span class="check">✅</span>测试全部通过</div><div class="item"><span class="check">✅</span>备份数据库</div><div class="item"><span class="check">✅</span>更新配置文件</div><div class="item"><span class="check">✅</span>执行部署脚本</div><div class="item"><span class="check">✅</span>验证服务正常</div></div><div class="footer">🐾 MOMO 帮你安全部署</div></div></body></html>
EOF

# Post 30 - 性能优化
cat > post-30.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 30</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#4facfe,#00f2fe);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.comparison{flex:1;display:flex;flex-direction:column;gap:30px}.bar-container{background:rgba(255,255,255,0.95);border-radius:15px;padding:25px}.label{font-size:24px;color:#333;margin-bottom:15px}.bar{height:40px;background:#f0f0f0;border-radius:10px;overflow:hidden}.fill{height:100%;background:linear-gradient(90deg,#4facfe,#00f2fe);display:flex;align-items:center;justify-content:flex-end;padding-right:15px;color:#fff;font-size:20px;font-weight:bold}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">⚡ 性能优化对比</h1></div><div class="comparison"><div class="bar-container"><div class="label">优化前</div><div class="bar"><div class="fill" style="width:40%">2.5s</div></div></div><div class="bar-container"><div class="label">优化后</div><div class="bar"><div class="fill" style="width:80%">0.3s</div></div></div></div><div class="footer">🐾 MOMO 帮你优化性能</div></div></body></html>
EOF

echo "✅ Posts 25-30 created"
