#!/bin/bash

# Post 31 - 学习路线
cat > post-31.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 31</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#d299c2,#fef9d7);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#333;font-weight:bold}.roadmap{flex:1;display:flex;flex-direction:column;gap:15px}.step{background:rgba(255,255,255,0.95);border-radius:15px;padding:20px;display:flex;align-items:center;gap:15px}.icon{font-size:40px}.text{font-size:20px;color:#333;flex:1}.footer{text-align:center;color:rgba(0,0,0,0.5);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">🗺️ Python 学习路线</h1></div><div class="roadmap"><div class="step"><div class="icon">1️⃣</div><div class="text">基础语法</div></div><div class="step"><div class="icon">2️⃣</div><div class="text">数据结构</div></div><div class="step"><div class="icon">3️⃣</div><div class="text">面向对象</div></div><div class="step"><div class="icon">4️⃣</div><div class="text">常用库</div></div><div class="step"><div class="icon">5️⃣</div><div class="text">实战项目</div></div></div><div class="footer">🐾 MOMO 陪你一步步学习</div></div></body></html>
EOF

# Post 32 - 技能树
cat > post-32.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 32</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#667eea,#764ba2);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.skills{flex:1;display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.skill{background:rgba(255,255,255,0.2);backdrop-filter:blur(10px);border-radius:20px;padding:25px;text-align:center;border:2px solid rgba(255,255,255,0.3)}.icon{font-size:50px;margin-bottom:15px}.name{font-size:18px;color:#fff;font-weight:600}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">🌳 我的技能树</h1></div><div class="skills"><div class="skill"><div class="icon">🐍</div><div class="name">Python</div></div><div class="skill"><div class="icon">📊</div><div class="name">数据分析</div></div><div class="skill"><div class="icon">🤖</div><div class="name">机器学习</div></div><div class="skill"><div class="icon">🌐</div><div class="name">Web 开发</div></div><div class="skill"><div class="icon">📱</div><div class="name">移动开发</div></div><div class="skill"><div class="icon">☁️</div><div class="name">云计算</div></div></div><div class="footer">🐾 MOMO 帮你点亮每个技能</div></div></body></html>
EOF

# Post 33 - 时间对比
cat > post-33.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 33</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#fa709a,#fee140);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.comparison{flex:1;display:flex;flex-direction:column;gap:30px}.item{background:rgba(255,255,255,0.95);border-radius:20px;padding:30px}.label{font-size:28px;color:#333;font-weight:bold;margin-bottom:20px}.time{font-size:48px;color:#fa709a;font-weight:bold}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">⏱️ 用 MOMO 前后对比</h1></div><div class="comparison"><div class="item"><div class="label">❌ 之前：整理笔记</div><div class="time">2 小时</div></div><div class="item"><div class="label">✅ 现在：整理笔记</div><div class="time">20 分钟</div></div><div class="item"><div class="label">❌ 之前：写报告</div><div class="time">4 小时</div></div><div class="item"><div class="label">✅ 现在：写报告</div><div class="time">1 小时</div></div></div><div class="footer">🐾 节省 75% 时间</div></div></body></html>
EOF

# Post 34 - 收入对比
cat > post-34.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 34</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#a8edea,#fed6e3);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#333;font-weight:bold}.savings{flex:1;background:rgba(255,255,255,0.95);border-radius:25px;padding:40px;display:flex;flex-direction:column;justify-content:center}.item{margin-bottom:30px}.label{font-size:26px;color:#666;margin-bottom:10px}.amount{font-size:56px;font-weight:bold}.other{color:#999}.momo{color:#11998e}.total{font-size:32px;color:#11998e;text-align:center;margin-top:30px}.footer{text-align:center;color:rgba(0,0,0,0.5);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">💰 一年省下多少钱</h1></div><div class="savings"><div class="item"><div class="label">某 Chat Plus</div><div class="amount other">¥240/年</div></div><div class="item"><div class="label">某 Copilot</div><div class="amount other">¥840/年</div></div><div class="item"><div class="label">🐾 MOMO</div><div class="amount momo">¥0/年</div></div><div class="total">✨ 一年省下 ¥1,080+</div></div><div class="footer">完全免费·开源透明</div></div></body></html>
EOF

# Post 35 - 成长记录
cat > post-35.html << 'EOF'
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>MOMO 配图 35</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;background:#000;display:flex;justify-content:center;align-items:center;min-height:100vh}.post{width:1080px;height:1440px;background:linear-gradient(135deg,#667eea,#764ba2);padding:60px;display:flex;flex-direction:column}.header{text-align:center;margin-bottom:40px}.title{font-size:64px;color:#fff;font-weight:bold}.timeline{flex:1;display:flex;flex-direction:column;gap:20px}.event{background:rgba(255,255,255,0.2);backdrop-filter:blur(10px);border-radius:15px;padding:20px;display:flex;align-items:center;gap:20px;border-left:4px solid #fff}.date{font-size:20px;color:#fff;font-weight:bold;min-width:120px}.desc{font-size:20px;color:#fff;flex:1}.footer{text-align:center;color:rgba(255,255,255,0.7);font-size:20px;margin-top:30px}</style></head><body><div class="post"><div class="header"><h1 class="title">📈 和 MOMO 一起成长</h1></div><div class="timeline"><div class="event"><div class="date">Day 1</div><div class="desc">第一次见面</div></div><div class="event"><div class="date">Week 1</div><div class="desc">帮我管理作业</div></div><div class="event"><div class="date">Month 1</div><div class="desc">成绩提升了</div></div><div class="event"><div class="date">Month 3</div><div class="desc">找到实习了</div></div><div class="event"><div class="date">Now</div><div class="desc">成为更好的自己</div></div></div><div class="footer">🐾 MOMO 陪你成长的每一天</div></div></body></html>
EOF

echo "✅ Posts 31-35 created"
